# Generated by Django 2.2.4 on 2019-09-13 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', editable=False, max_length=50)),
                ('last_name', models.CharField(default='', editable=False, max_length=50)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(default='', editable=False, max_length=2)),
                ('address', models.CharField(default='', editable=False, max_length=100)),
                ('email', models.EmailField(default='', editable=False, max_length=30)),
            ],
        ),
    ]
